### PR TITLE
This makes `bin/cuke_cataloger` executable using chmod +x

### PR DESCRIPTION
**Pull request by alexanderjeurissen**
When running `bundle exec rake cuke_cataloger:smart_test` the following spec failure occurred:

image

Turns out the `bin/cuke_cataloger` was not executable, I fixed it using `chmod +x bin/cuke_cataloger`

### CODE REVIEW

**Comment by enkessler** [comment]
How are you running the tests? That failure pops up for you but not in the CI at all or locally for me when I run the tests.

**Comment by alexanderjeurissen** [comment]
@enkessler I run it locally on Mac OS (patch before big sur). With ruby 2.6.6.

I run it exactly as specified in the PR description:

`bundle exec rake cuke_cataloger:smart_test`

**Comment by enkessler** [comment]
On the one hand, I'm pretty sure that this is a good change to make because an executable file probably ought to be marked as such and Git is showing that it is saved as a non-executable file (e.g. 100644). On the other hand, I'm still very curious as to why the file is sometimes executable and sometimes not, depending on what file system it is placed on. When I look at my locale copy, it is marked as executable and, presumably, it is marked as executable in other places where that test is run and, naturally, the gem has been published for years and the executable works fine when the gem is used in the real world.

**Comment by enkessler** [comment]
@alexanderjeurissen *poke*

**In summary**: I'll be fine with this change as soon as I understand why it hasn't been a problem before now. Feel free to dump additional knowledge on me in order to reach that goal.

**Pull request merged**
